const WIDTH = 5000;
const HEIGHT = 5000;

const N_XP_BUBBLE = 300;
const N_HEALTH_BUBBLE = 15;

const BULLET_SPEED = 15;
const BULLET_DAMAGE = 5;

export default {
  WIDTH,
  HEIGHT,
  N_XP_BUBBLE,
  N_HEALTH_BUBBLE,
  BULLET_SPEED,
  BULLET_DAMAGE,
};
